runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
            python_version: 3
env_variables:
            CLOUD_STORAGE_BUCKET: vgan10
resources:
    cpu: 1
    memory_gb: 2
    disk_size_gb: 1
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 400
manual_scaling:
    instances: 1
