runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
            python_version: 3
env_variables:
            CLOUD_STORAGE_BUCKET: vgan10
resources:
        disk_size_gb: 20

manual_scaling:
        instances: 1
